export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS';
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS';
export const REJECT_ALL_USERS = 'REJECT_ALL_USERS';

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const REQUEST_RECEIVE_NEW_USER = 'REQUEST_RECEIVE_NEW_USER';
export const REQUEST_REJECT_NEW_USER = 'RREQUEST_REJECT_NEW_USER';
