export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS';
export const RECEIVE_ALL_USERS = 'RECEIVE_ALL_USERS';
export const REJECT_ALL_USERS = 'REJECT_ALL_USERS';

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const REQUEST_RECEIVE_NEW_USER = 'REQUEST_RECEIVE_NEW_USER';
export const REQUEST_REJECT_NEW_USER = 'RREQUEST_REJECT_NEW_USER';

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const REJECT_USER = 'REJECT_USER';

export const REQUEST_EDIT_USER = 'REQUEST_EDIT_USER';
export const RECEIVE_EDIT_USER = 'RECEIVE_EDIT_USER';
export const REJECT_EDIT_USER = 'REJECT_EDIT_USER';

export const REQUEST_DELETE_USER = 'REQUEST_DELETE_USER';
export const RECEIVE_DELETE_USER = 'RECEIVE_DELETE_USER';
export const REJECT_DELETE_USER = 'REJECT_DELETE_USER';
